require('dotenv').config();

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const express = require('express');
const cors = require('cors');
const morgan = require('morgan');
const multer = require('multer');
const XLSX = require('xlsx');
const { google } = require('googleapis');

const app = express();
const PORT = Number(process.env.PORT || 8080);
const ROOT = __dirname;
const SCHEMA = require('./columns.json');

const DATA_DIR = process.env.DATA_DIR || path.join(ROOT, 'data');
const DATA_FILE = path.join(DATA_DIR, 'cases.json');
const TEMPLATE_FILE = path.join(ROOT, 'templates', 'EEMS案件審核匯入匯出範本.xlsx');
const UPLOAD_DIR = path.join(DATA_DIR, 'uploads');

const upload = multer({ dest: UPLOAD_DIR });
const AI_PROVIDER = (process.env.AI_PROVIDER || 'heuristic').toLowerCase();
const AI_MODEL = process.env.AI_MODEL || 'gpt-4.1-mini';

fs.mkdirSync(DATA_DIR, { recursive: true });
fs.mkdirSync(UPLOAD_DIR, { recursive: true });
if (!fs.existsSync(DATA_FILE)) fs.writeFileSync(DATA_FILE, '[]', 'utf8');

const corsOptions = process.env.ALLOWED_ORIGIN
  ? { origin: process.env.ALLOWED_ORIGIN }
  : {};
app.use(cors(corsOptions));
app.use(express.json({ limit: '8mb' }));
app.use(morgan('tiny'));
app.use(express.static(path.join(ROOT, 'public')));

function nowTaipei() {
  return new Date().toISOString();
}

function todayTaipeiDate() {
  const dtf = new Intl.DateTimeFormat('sv-SE', {
    timeZone: 'Asia/Taipei',
    year: 'numeric',
    month: '2-digit',
    day: '2-digit'
  });
  return dtf.format(new Date());
}

function readCases() {
  try {
    const raw = fs.readFileSync(DATA_FILE, 'utf8');
    return JSON.parse(raw || '[]');
  } catch (err) {
    console.error('readCases failed:', err);
    return [];
  }
}

function writeCases(cases) {
  cases.forEach((item) => {
    if (!item.uid) item.uid = caseKey(item) || ('UID-' + crypto.randomUUID().replace(/-/g, '').slice(0, 16).toUpperCase());
    if (isAutoGeneratedCaseNo(item.id) && !item.source?.['案件編號']) item.id = '';
  });
  fs.writeFileSync(DATA_FILE, JSON.stringify(refreshRepeatFlags(cases), null, 2), 'utf8');
}

function addLog(item, action, by, note = '') {
  item.logs = Array.isArray(item.logs) ? item.logs : [];
  item.logs.unshift({ at: nowTaipei(), action, by: by || 'system', note });
  item.updatedAt = nowTaipei();
}

function normalizeText(value) {
  if (value === null || value === undefined) return '';
  if (value instanceof Date) return value.toISOString().slice(0, 10);
  return String(value).trim();
}

function normalizeHeaderName(value) {
  return normalizeText(value).replace(/\s+/g, '');
}

const HEADER_ALIASES = {
  '稽查編號': '稽查單號',
  '稽查單號': '稽查單號',
  '告發單號': '告發單號',
  '公文案號': '公文文號',
  '公文日期': '發文日期',
  '裁處書號': '裁處字號',
  '送達狀態': '送達日期'
};

function canonicalHeader(value) {
  const key = normalizeHeaderName(value);
  return HEADER_ALIASES[key] || key;
}

function canonicalizeRow(row = {}) {
  const out = {};
  Object.entries(row).forEach(([key, value]) => {
    const canonical = canonicalHeader(key);
    if (canonical) out[canonical] = value;
    const trimmed = normalizeText(key);
    if (trimmed && !Object.prototype.hasOwnProperty.call(out, trimmed)) out[trimmed] = value;
  });
  return out;
}

function firstNonEmpty(...values) {
  for (const value of values) {
    const v = normalizeText(value);
    if (v) return v;
  }
  return '';
}

function digitsOnly(value) {
  return normalizeText(value).replace(/\D/g, '');
}

function formatDispositionNo(value) {
  const d = digitsOnly(value);
  if (!d) return '';
  if (d.length === 11) return `${d.slice(0, 2)}-${d.slice(2, 5)}-${d.slice(5)}`;
  return normalizeText(value);
}

function getCaseIdentifier(type, row = {}) {
  const canonical = canonicalizeRow(row);
  if (type === '告發') {
    return firstNonEmpty(canonical['案件編號'], canonical['稽查單號'], canonical['告發單號']);
  }
  return firstNonEmpty(canonical['案件編號']);
}

function getSourceValue(source = {}, header) {
  const key = canonicalHeader(header);
  return firstNonEmpty(source[key], source[header], key === '稽查單號' ? source['稽查編號'] : '');
}

function hasMeaningfulCaseRow(type, row = {}) {
  const canonical = canonicalizeRow(row);
  return Boolean(
    firstNonEmpty(canonical['車號'], canonical['案件編號'], canonical['稽查單號'], canonical['告發單號']) ||
    (type === '通檢' && firstNonEmpty(canonical['車號'], canonical['量測日期'], canonical['量測位置地點']))
  );
}

function parseBool(value) {
  if (typeof value === 'boolean') return value;
  const v = normalizeText(value).toLowerCase();
  return ['true', '1', 'yes', 'y', '是', '核可', '已核可', 'v', '✓', '勾選'].includes(v);
}

function isRepeatSource(source = {}) {
  // 修正：前次告發僅作為人工參考，不再因欄位有文字就直接判斷加重。
  return parseBool(source['是否累犯']) || parseBool(source['1年內再次違反']);
}

function caseNeedsEscalation(item) {
  return Boolean(item?.flags?.repeatOverLimit || item?.flags?.escalated || isRepeatSource(item?.source));
}

function refreshRepeatFlags(cases) {
  const plateCounts = new Map();
  cases.forEach((item) => {
    const plate = normalizeText(item?.source?.['車號']).toUpperCase();
    if (plate) plateCounts.set(plate, (plateCounts.get(plate) || 0) + 1);
  });

  cases.forEach((item) => {
    const plate = normalizeText(item?.source?.['車號']).toUpperCase();
    const count = plate ? (plateCounts.get(plate) || 0) : 0;
    const sourceRepeat = isRepeatSource(item?.source);
    item.flags = item.flags || {};
    item.flags.plateRepeatCount = count;
    item.flags.repeatOverLimit = Boolean(plate && count > 1) || sourceRepeat;
    item.flags.escalated = item.flags.repeatOverLimit;
    item.flags.repeatNote = item.flags.repeatOverLimit
      ? `車號重複超標${count > 1 ? count + '件' : ''}，註明加重`
      : '';
  });
  return cases;
}

function isAutoGeneratedCaseNo(value) {
  return /^[AI]-[A-F0-9]{10}$/.test(normalizeText(value));
}

function makeInternalUid(type, row = {}, source = {}) {
  const canonical = canonicalizeRow(row);
  const seed = [
    type,
    canonical['案件編號'],
    canonical['稽查單號'],
    canonical['告發單號'],
    source['車號'],
    source['量測日期'],
    source['稽查時間'],
    source['量測位置地點']
  ].filter((v) => normalizeText(v)).join('|') || crypto.randomUUID();
  return 'UID-' + crypto.createHash('sha1').update(seed).digest('hex').slice(0, 16).toUpperCase();
}

function caseKey(item = {}) {
  return normalizeText(item.uid || item.internalId || item._uid || item.id);
}

function publicCaseNo(item = {}) {
  const no = normalizeText(item.id || item.caseNo || item.source?.['案件編號']);
  return isAutoGeneratedCaseNo(no) ? '' : no;
}

function displayCaseTitle(item = {}) {
  return publicCaseNo(item) || normalizeText(item.source?.['稽查單號'] || item.source?.['稽查編號'] || item.source?.['告發單號']) || caseKey(item);
}

function findCaseIndexById(cases, id) {
  const key = normalizeText(id);
  return cases.findIndex((c) => caseKey(c) === key || normalizeText(c.id) === key);
}

function requireDeleteAdmin(req, res, next) {
  const required = process.env.ADMIN_DELETE_PASSCODE || '69677323';
  const provided = req.header('x-admin-delete-passcode') || req.body?.adminPassword || req.query.adminPassword;
  if (provided === required) return next();
  return res.status(403).json({ error: '刪除案件需要管理權限密碼。' });
}

function cleanObjectByHeaders(row, headers) {
  const canonical = canonicalizeRow(row);
  const out = {};
  headers.forEach((h) => {
    out[h] = normalizeText(canonical[h]);
  });
  // 兼容舊版資料與局端表單曾使用的「稽查編號」欄名。
  if (!out['稽查單號'] && canonical['稽查編號']) out['稽查單號'] = normalizeText(canonical['稽查編號']);
  return out;
}

function buildCaseId(type, row, source) {
  // 案件編號是局端資料欄位，未填時需保留空白，不能由系統自動補號。
  const canonical = canonicalizeRow(row);
  return normalizeText(canonical['案件編號'] || source['案件編號']);
}

function statusFromRow(row, type) {
  const explicit = normalizeText(row['案件狀態']);
  if (explicit) return explicit;
  if (parseBool(row['長官核可'])) return '行政處理中';
  if (normalizeText(row['退回原因'])) return '退回修正';
  return '待長官審核';
}

function caseFromFlatRow(type, row, options = {}) {
  if (!SCHEMA[type]) throw new Error(`不支援的案件類型：${type}`);
  row = canonicalizeRow(row);
  const source = cleanObjectByHeaders(row, SCHEMA[type].sourceHeaders);
  source['案件編號'] = normalizeText(row['案件編號']);
  const id = buildCaseId(type, row, source);
  const uid = makeInternalUid(type, row, source);
  const chiefApproved = parseBool(row['長官核可']);
  const status = statusFromRow(row, type);
  const item = {
    uid,
    id,
    type,
    status,
    source,
    review: {
      consultantChecked: parseBool(row['顧問初核']) || parseBool(row['承辦複核']) || parseBool(row['備註']),
      consultantReviewer: normalizeText(row['承辦人員']) || '聯韻初核',
      submittedAt: normalizeText(row['送審日期']) || todayTaipeiDate(),
      chiefApproved,
      chiefReviewer: normalizeText(row['長官姓名']),
      chiefReviewedAt: normalizeText(row['核可日期']),
      rejectedReason: normalizeText(row['退回原因'])
    },
    admin: {
      stage: normalizeText(row['行政流程階段']) || (chiefApproved ? '待製作公文' : '尚未啟動'),
      officialDocumentNo: normalizeText(row['公文文號']) || normalizeText(row['公文案號']),
      officialDocumentDate: normalizeText(row['發文日期']) || normalizeText(row['公文日期']),
      dispositionNo: normalizeText(row['裁處字號']) || normalizeText(row['裁處書號']),
      penaltyAmount: normalizeText(row['裁罰金額']) || normalizeText(row['金額']),
      deliveryDate: normalizeText(row['送達日期']) || normalizeText(row['送達狀態']),
      paymentStatus: normalizeText(row['繳款狀態']) || '尚未繳款',
      inspectionDueDate: normalizeText(row['通檢期限']),
      inspectionStatus: normalizeText(row['到檢狀態']) || (type === '通檢' ? '通知待發文' : '未啟動'),
      closeDate: normalizeText(row['結案日期']),
      notes: normalizeText(row['行政備註'])
    },
    flags: {
      repeatOverLimit: isRepeatSource(source),
      escalated: isRepeatSource(source),
      repeatNote: isRepeatSource(source) ? '車號重複超標，註明加重' : '',
      plateRepeatCount: 0
    },
    logs: [],
    createdAt: nowTaipei(),
    updatedAt: nowTaipei()
  };
  addLog(item, '匯入案件', 'system', `${type}固定格式匯入`);
  return item;
}

function toFlatRow(item) {
  const sourceHeaders = SCHEMA[item.type].sourceHeaders;
  const row = {};
  sourceHeaders.forEach((h) => { row[h] = getSourceValue(item.source, h); });
  row['案件編號'] = publicCaseNo(item);
  row['案件類型'] = item.type;
  row['案件狀態'] = item.status;
  row['顧問初核'] = item.review?.consultantChecked ? 'TRUE' : '';
  row['承辦人員'] = item.review?.consultantReviewer || '';
  row['送審日期'] = item.review?.submittedAt || '';
  row['長官核可'] = item.review?.chiefApproved ? 'TRUE' : '';
  row['長官姓名'] = item.review?.chiefReviewer || '';
  row['核可日期'] = item.review?.chiefReviewedAt || '';
  row['退回原因'] = item.review?.rejectedReason || '';
  row['行政流程階段'] = item.admin?.stage || '';
  row['公文文號'] = item.admin?.officialDocumentNo || '';
  row['發文日期'] = item.admin?.officialDocumentDate || '';
  row['裁處字號'] = formatDispositionNo(item.admin?.dispositionNo || '');
  row['裁罰金額'] = item.admin?.penaltyAmount || '';
  row['送達日期'] = item.admin?.deliveryDate || item.admin?.deliveryStatus || '';
  row['繳款狀態'] = item.admin?.paymentStatus || '';
  row['通檢期限'] = item.admin?.inspectionDueDate || '';
  row['到檢狀態'] = item.admin?.inspectionStatus || '';
  row['結案日期'] = item.admin?.closeDate || '';
  row['行政備註'] = item.admin?.notes || '';
  row['重複超標註記'] = caseNeedsEscalation(item) ? (item.flags?.repeatNote || '車號重複超標，註明加重') : '';
  row['更新時間'] = item.updatedAt || '';
  return row;
}

function exportHeaders(type) {
  return [...SCHEMA[type].sourceHeaders, ...SCHEMA.workflowHeaders];
}

function rowsToSheetValues(type, cases) {
  refreshRepeatFlags(cases);
  const headers = exportHeaders(type);
  const dataRows = cases
    .filter((c) => c.type === type)
    .map((c) => {
      const row = toFlatRow(c);
      return headers.map((h) => row[h] ?? '');
    });
  return [headers, ...dataRows];
}

function makeWorkbookForCases(type, cases) {
  refreshRepeatFlags(cases);
  const wb = XLSX.utils.book_new();
  if (type === '全部') {
    ['告發', '通檢'].forEach((t) => {
      const ws = XLSX.utils.aoa_to_sheet(rowsToSheetValues(t, cases));
      XLSX.utils.book_append_sheet(wb, ws, t);
    });
  } else {
    const ws = XLSX.utils.aoa_to_sheet(rowsToSheetValues(type, cases));
    XLSX.utils.book_append_sheet(wb, ws, type);
  }
  const logRows = [['案件編號', '時間', '動作', '執行者', '備註']];
  cases.forEach((c) => {
    (c.logs || []).forEach((log) => logRows.push([publicCaseNo(c), log.at, log.action, log.by, log.note]));
  });
  XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(logRows), '案件追蹤紀錄');
  return wb;
}

function readUploadedWorkbook(filePath, preferredType) {
  const wb = XLSX.readFile(filePath, { cellDates: true, raw: false, defval: '' });
  const sheetName = wb.SheetNames.includes(preferredType) ? preferredType : wb.SheetNames[0];
  const ws = wb.Sheets[sheetName];
  const rows = XLSX.utils.sheet_to_json(ws, { defval: '', raw: false });
  return rows;
}

function upsertCases(existing, incoming) {
  existing.forEach((item) => {
    if (!item.uid) item.uid = caseKey(item) || ('UID-' + crypto.randomUUID().replace(/-/g, '').slice(0, 16).toUpperCase());
    if (isAutoGeneratedCaseNo(item.id) && !item.source?.['案件編號']) item.id = '';
  });
  const map = new Map(existing.map((item) => [caseKey(item), item]));
  let inserted = 0;
  let updated = 0;
  incoming.forEach((item) => {
    if (!item.uid) item.uid = caseKey(item) || ('UID-' + crypto.randomUUID().replace(/-/g, '').slice(0, 16).toUpperCase());
    const key = caseKey(item);
    if (map.has(key)) {
      const old = map.get(key);
      const merged = {
        ...old,
        ...item,
        uid: old.uid || item.uid,
        logs: [...(item.logs || []), ...(old.logs || [])],
        createdAt: old.createdAt || item.createdAt,
        updatedAt: nowTaipei()
      };
      // Google Sheet 若案件編號空白，系統內也保留空白，不回填內部識別碼。
      merged.id = publicCaseNo(item);
      map.set(key, merged);
      updated += 1;
    } else {
      item.id = publicCaseNo(item);
      map.set(key, item);
      inserted += 1;
    }
  });
  return { cases: refreshRepeatFlags(Array.from(map.values())), inserted, updated };
}

function filterCases(cases, query) {
  let out = cases;
  if (query.type && query.type !== '全部') out = out.filter((c) => c.type === query.type);
  if (query.status && query.status !== '全部') out = out.filter((c) => c.status === query.status);
  if (query.q) {
    const q = String(query.q).toLowerCase();
    out = out.filter((c) => JSON.stringify(c).toLowerCase().includes(q));
  }
  return out;
}

function stats(cases) {
  const byStatus = {};
  const byType = {};
  const byTypeDetail = {};
  SCHEMA.statusOptions.forEach((s) => { byStatus[s] = 0; });
  ['告發', '通檢'].forEach((t) => {
    byType[t] = 0;
    byTypeDetail[t] = {
      total: 0,
      pendingReview: 0,
      approved: 0,
      adminProcessing: 0,
      closed: 0
    };
  });
  cases.forEach((c) => {
    const type = c.type || '未分類';
    byStatus[c.status] = (byStatus[c.status] || 0) + 1;
    byType[type] = (byType[type] || 0) + 1;
    if (!byTypeDetail[type]) byTypeDetail[type] = { total: 0, pendingReview: 0, approved: 0, adminProcessing: 0, closed: 0 };
    byTypeDetail[type].total += 1;
    if (c.status === '待長官審核') byTypeDetail[type].pendingReview += 1;
    if (c.review?.chiefApproved) byTypeDetail[type].approved += 1;
    if (c.status === '行政處理中') byTypeDetail[type].adminProcessing += 1;
    if (c.status === '已結案') byTypeDetail[type].closed += 1;
  });
  const approved = cases.filter((c) => c.review?.chiefApproved).length;
  return {
    total: cases.length,
    byStatus,
    byType,
    byTypeDetail,
    pendingReview: cases.filter((c) => c.status === '待長官審核').length,
    approved,
    reviewedTotal: approved,
    adminProcessing: cases.filter((c) => c.status === '行政處理中').length,
    closed: cases.filter((c) => c.status === '已結案').length
  };
}


function parseNumber(value) {
  const match = normalizeText(value).replace(',', '.').match(/-?\d+(?:\.\d+)?/);
  return match ? Number(match[0]) : null;
}

function parseTaipeiDate(value) {
  const v = normalizeText(value);
  if (!v) return null;
  const roc = v.match(/^(\d{2,3})[./-](\d{1,2})[./-](\d{1,2})/);
  if (roc) return new Date(Date.UTC(Number(roc[1]) + 1911, Number(roc[2]) - 1, Number(roc[3])));
  const ce = v.match(/^(\d{4})[./-](\d{1,2})[./-](\d{1,2})/);
  if (ce) return new Date(Date.UTC(Number(ce[1]), Number(ce[2]) - 1, Number(ce[3])));
  const d = new Date(v);
  return Number.isNaN(d.getTime()) ? null : d;
}

function daysBetweenToday(value) {
  const d = parseTaipeiDate(value);
  if (!d) return null;
  const today = parseTaipeiDate(todayTaipeiDate());
  return Math.round((d.getTime() - today.getTime()) / 86400000);
}

function plateFormatOk(plate) {
  const p = normalizeText(plate).toUpperCase().replace(/\s+/g, '');
  if (!p) return false;
  return /^[A-Z0-9]{2,4}-?[A-Z0-9]{2,4}$/.test(p) && p.length >= 5;
}

function aiQualityCheck(item) {
  const s = item.source || {};
  const issues = [];
  const warnings = [];
  const ok = [];
  const db = parseNumber(s['背景修正後分貝']);
  const std = parseNumber(s['管制標準']);
  const limit = parseNumber(s['路段限速'] || s['限速']);
  const plate = normalizeText(s['車號']);
  const location = caseLocationServer(item);
  if (!publicCaseNo(item)) warnings.push('案件編號空白：可匯入，但建議行政處理前補正。');
  else ok.push('案件編號已填。');
  if (!plate) issues.push('車號空白。');
  else if (!plateFormatOk(plate)) warnings.push('車號格式疑似異常，建議人工確認。');
  else ok.push('車號格式正常。');
  if (db === null) issues.push('背景修正後分貝缺漏或無法判讀。');
  if (std === null) warnings.push('管制標準缺漏，無法自動確認超標條件。');
  if (db !== null && std !== null) {
    if (db >= std) ok.push(`背景修正後 ${db}dB，高於標準 ${std}dB，超標 ${Number((db - std).toFixed(1))}dB。`);
    else issues.push(`背景修正後 ${db}dB 未達管制標準 ${std}dB，請確認是否應列案。`);
  }
  if (limit !== null && std !== null) {
    if (limit <= 50 && std !== 86) warnings.push('限速 50km/h 以下通常應對應 86dB，請確認管制標準。');
    if (limit > 50 && limit <= 70 && std !== 90) warnings.push('限速 50–70km/h 通常應對應 90dB，請確認管制標準。');
  }
  if (!normalizeText(s['量測日期'])) issues.push('量測日期空白。');
  else ok.push('量測日期已填。');
  if (!location) warnings.push('量測位置地點空白或不足。');
  if (item.flags?.plateRepeatCount > 1) warnings.push(`同車號目前累計 ${item.flags.plateRepeatCount} 筆，建議人工確認是否屬重複超標或應加重。`);
  const level = issues.length ? 'error' : warnings.length ? 'warning' : 'ok';
  const label = level === 'error' ? '高風險錯誤' : level === 'warning' ? '建議補正' : '資料完整';
  return { level, label, issues, warnings, ok, checkedAt: nowTaipei() };
}

function caseLocationServer(item) {
  const s = item.source || {};
  return firstNonEmpty(s['量測位置地點'], `${s['便於複製(行政區)'] || ''}${s['便於複製(路段)'] || ''}`);
}

function dbTextServer(item) {
  const s = item.source || {};
  return [s['背景修正後分貝'], s['管制標準']].filter((v) => normalizeText(v)).join(' / ');
}

function aiPriority(item) {
  const q = aiQualityCheck(item);
  const s = item.source || {};
  const db = parseNumber(s['背景修正後分貝']);
  const std = parseNumber(s['管制標準']);
  let score = 0;
  const reasons = [];
  if (db !== null && std !== null && db >= std) {
    const over = db - std;
    score += Math.min(40, Math.round(over * 6));
    reasons.push(`超標 ${Number(over.toFixed(1))}dB`);
  }
  if (item.status === '待長官審核') { score += 18; reasons.push('待長官審核'); }
  if (item.status === '行政處理中') { score += 12; reasons.push('行政處理中'); }
  if (item.flags?.plateRepeatCount > 1 || item.flags?.repeatOverLimit || item.flags?.escalated) { score += 20; reasons.push('疑似重複超標／加重'); }
  if (q.level === 'error') { score += 16; reasons.push('資料有高風險錯誤'); }
  if (q.level === 'warning') { score += 8; reasons.push('資料建議補正'); }
  const due = daysBetweenToday(item.admin?.inspectionDueDate);
  if (due !== null && due <= 3 && item.status !== '已結案') { score += 18; reasons.push(`通檢期限剩 ${due} 日`); }
  if (item.review?.chiefApproved && !item.admin?.officialDocumentNo && item.status !== '已結案') { score += 15; reasons.push('已核可但未填公文文號'); }
  if (item.type === '告發' && item.review?.chiefApproved && !item.admin?.dispositionNo && item.status !== '已結案') { score += 10; reasons.push('已核可但未填裁處字號'); }
  const rank = score >= 70 ? 'S' : score >= 45 ? 'A' : score >= 25 ? 'B' : 'C';
  return { score, rank, reasons };
}

function aiSummary(item) {
  const s = item.source || {};
  const q = aiQualityCheck(item);
  const p = aiPriority(item);
  const db = parseNumber(s['背景修正後分貝']);
  const std = parseNumber(s['管制標準']);
  const overText = db !== null && std !== null ? `，超標 ${Number((db - std).toFixed(1))}dB` : '';
  const title = displayCaseTitle(item);
  const summary = `本案為${item.type}案件，案件識別為 ${title || '未填案件編號'}，車號 ${s['車號'] || '未填'}，於 ${[s['量測日期'], s['稽查時間']].filter(Boolean).join(' ') || '未填量測時間'} 在 ${caseLocationServer(item) || '未填地點'} 測得 ${dbTextServer(item) || '未填分貝/標準'}${overText}。目前狀態為「${item.status || '未分類'}」，AI 優先等級為 ${p.rank} 級。`;
  const recommendation = q.level === 'error'
    ? '建議先退回或人工補正後再送長官核可。'
    : item.status === '待長官審核'
      ? '資料未見重大阻卻事項，可供長官審核參考；仍應由承辦確認原始影像與法定要件。'
      : item.review?.chiefApproved
        ? '已核可案件，建議依行政待辦提醒補齊公文、裁處、送達、繳款或通檢進度。'
        : '建議由承辦確認案件狀態與補件需求。';
  return { summary, recommendation, quality: q, priority: p };
}

function aiRejectReason(item) {
  const q = aiQualityCheck(item);
  const reasons = [...q.issues, ...q.warnings];
  if (!reasons.length) reasons.push('案件仍需承辦補充原始佐證資料或確認法定要件。');
  return `本案建議退回補正，原因如下：\n${reasons.map((r, i) => `${i + 1}. ${r}`).join('\n')}\n請補正後重新送審。`;
}

function aiAdminTasks(cases) {
  return refreshRepeatFlags(cases).flatMap((item) => {
    const tasks = [];
    if (item.status === '已結案') return tasks;
    if (item.review?.chiefApproved && !item.admin?.officialDocumentNo) tasks.push({ level: 'high', caseId: caseKey(item), title: '已核可但未填公文文號', action: '請確認是否已發文並補填公文文號。' });
    if (item.type === '告發' && item.review?.chiefApproved && !item.admin?.dispositionNo) tasks.push({ level: 'medium', caseId: caseKey(item), title: '告發案件未填裁處字號', action: '請確認裁處書製作進度。' });
    const due = daysBetweenToday(item.admin?.inspectionDueDate);
    if (due !== null && due <= 7 && item.type === '通檢') tasks.push({ level: due <= 3 ? 'high' : 'medium', caseId: caseKey(item), title: `通檢期限剩 ${due} 日`, action: '請確認通知、到檢與後續追蹤。' });
    if (item.admin?.officialDocumentNo && !item.admin?.deliveryDate) tasks.push({ level: 'medium', caseId: caseKey(item), title: '已發文但未填送達日期', action: '請補填送達日期或確認送達狀態。' });
    return tasks.map((task) => ({ ...task, type: item.type, plate: item.source?.['車號'] || '', displayNo: displayCaseTitle(item), status: item.status }));
  }).sort((a, b) => {
    const order = { high: 0, medium: 1, low: 2 };
    return (order[a.level] ?? 9) - (order[b.level] ?? 9);
  });
}

function aiDashboard(cases) {
  const refreshed = refreshRepeatFlags(cases);
  const quality = refreshed.map((item) => ({ item, quality: aiQualityCheck(item), priority: aiPriority(item) }));
  const priorityList = quality
    .map(({ item, quality, priority }) => ({ caseId: caseKey(item), displayNo: displayCaseTitle(item), type: item.type, plate: item.source?.['車號'] || '', status: item.status, quality, priority }))
    .sort((a, b) => b.priority.score - a.priority.score)
    .slice(0, 10);
  const tasks = aiAdminTasks(refreshed).slice(0, 10);
  return {
    provider: AI_PROVIDER,
    model: AI_MODEL,
    generatedAt: nowTaipei(),
    counts: {
      qualityError: quality.filter((x) => x.quality.level === 'error').length,
      qualityWarning: quality.filter((x) => x.quality.level === 'warning').length,
      qualityOk: quality.filter((x) => x.quality.level === 'ok').length,
      adminTasks: aiAdminTasks(refreshed).length
    },
    priorityList,
    tasks
  };
}

function aiLineAnswer(query, cases) {
  const q = normalizeText(query).toLowerCase();
  const refreshed = refreshRepeatFlags(cases);
  if (!q) return '請輸入查詢條件，例如：查 ABC-1234、今天待審案件、行政待辦。';
  if (q.includes('待審')) {
    const pending = refreshed.filter((c) => c.status === '待長官審核');
    return `目前待長官審核 ${pending.length} 件。\n${pending.slice(0, 5).map((c, i) => `${i + 1}. ${c.source?.['車號'] || '未填車號'}｜${displayCaseTitle(c)}｜${caseLocationServer(c) || '未填地點'}`).join('\n') || '目前沒有待審案件。'}`;
  }
  if (q.includes('待辦') || q.includes('逾期')) {
    const tasks = aiAdminTasks(refreshed).slice(0, 8);
    return `AI 行政待辦 ${tasks.length} 件：\n${tasks.map((t, i) => `${i + 1}. ${t.plate || '未填車號'}｜${t.title}｜${t.action}`).join('\n') || '目前沒有明顯行政待辦。'}`;
  }
  const hit = refreshed.find((c) => JSON.stringify(c).toLowerCase().includes(q.replace(/^查\s*/, '')));
  if (!hit) return '查無符合案件，請改用車號、案件編號、稽查單號或地點查詢。';
  const sum = aiSummary(hit);
  return `${sum.summary}\nAI 建議：${sum.recommendation}`;
}


function safeCaseForAi(item) {
  const s = item.source || {};
  return {
    caseId: displayCaseTitle(item),
    type: item.type,
    status: item.status,
    plateMasked: normalizeText(s['車號']).replace(/(.{2}).+(.{2})/, '$1****$2'),
    vehicleType: s['車種'] || '',
    measureDate: s['量測日期'] || '',
    measureTime: s['稽查時間'] || '',
    districtOrRoad: firstNonEmpty(s['便於複製(行政區)'], s['便於複製(路段)'], s['量測位置地點']),
    dbCorrected: s['背景修正後分貝'] || '',
    standardDb: s['管制標準'] || '',
    review: item.review || {},
    admin: item.admin || {},
    flags: item.flags || {}
  };
}

async function callOpenAiText(systemPrompt, userPayload) {
  if (AI_PROVIDER !== 'openai' || !process.env.OPENAI_API_KEY) return '';
  const endpoint = process.env.OPENAI_BASE_URL || 'https://api.openai.com/v1/chat/completions';
  const response = await fetch(endpoint, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${process.env.OPENAI_API_KEY}`
    },
    body: JSON.stringify({
      model: AI_MODEL,
      temperature: 0.2,
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: JSON.stringify(userPayload) }
      ]
    })
  });
  if (!response.ok) {
    const text = await response.text();
    throw new Error(`OpenAI API 呼叫失敗：${response.status} ${text.slice(0, 200)}`);
  }
  const data = await response.json();
  return data?.choices?.[0]?.message?.content?.trim() || '';
}

async function aiSummaryEnhanced(item) {
  const base = aiSummary(item);
  const llmText = await callOpenAiText(
    '你是新北市環保局聲音照相案件審核輔助工具。請根據脫敏案件資料，用繁體中文產生精簡案件摘要與承辦建議。不得主張 AI 可取代長官核可或裁罰決定。',
    { case: safeCaseForAi(item), base }
  );
  return llmText ? { ...base, llmText } : base;
}

async function aiRejectReasonEnhanced(item) {
  const base = aiRejectReason(item);
  const llmText = await callOpenAiText(
    '你是行政案件補正文字助手。請根據脫敏案件資料與規則檢查結果，產生可貼入退回原因欄位的繁體中文文字，條列、精簡、避免個資。',
    { case: safeCaseForAi(item), baseRejectReason: base, quality: aiQualityCheck(item) }
  );
  return llmText || base;
}

async function aiLineAnswerEnhanced(query, cases) {
  const base = aiLineAnswer(query, cases);
  if (AI_PROVIDER !== 'openai' || !process.env.OPENAI_API_KEY) return base;
  const dashboard = aiDashboard(cases);
  const llmText = await callOpenAiText(
    '你是 LINE Bot 查詢助理。請根據系統已計算的結果回覆繁體中文，簡潔、適合 LINE 訊息，不要揭露個資。',
    { query, baseAnswer: base, dashboard: { counts: dashboard.counts, priorityList: dashboard.priorityList.slice(0, 5), tasks: dashboard.tasks.slice(0, 5) } }
  );
  return llmText || base;
}

function authGuard(req, res, next) {
  const required = process.env.APP_PASSCODE;
  if (!required) return next();
  const provided = req.header('x-app-passcode') || req.query.passcode;
  if (provided === required) return next();
  return res.status(401).json({ error: '未授權：請輸入內部驗證碼。' });
}

app.use('/api', authGuard);

async function getSheetsClient() {
  const sheetId = process.env.GOOGLE_SHEET_ID;
  if (!sheetId) throw new Error('尚未設定 GOOGLE_SHEET_ID');

  let credentials = null;
  if (process.env.GOOGLE_SERVICE_ACCOUNT_JSON_BASE64) {
    const raw = Buffer.from(process.env.GOOGLE_SERVICE_ACCOUNT_JSON_BASE64, 'base64').toString('utf8');
    credentials = JSON.parse(raw);
  } else if (process.env.GOOGLE_SERVICE_ACCOUNT_JSON) {
    credentials = JSON.parse(process.env.GOOGLE_SERVICE_ACCOUNT_JSON);
  } else {
    throw new Error('尚未設定 GOOGLE_SERVICE_ACCOUNT_JSON 或 GOOGLE_SERVICE_ACCOUNT_JSON_BASE64');
  }

  const auth = new google.auth.GoogleAuth({
    credentials,
    scopes: ['https://www.googleapis.com/auth/spreadsheets']
  });
  const sheets = google.sheets({ version: 'v4', auth });
  return { sheets, sheetId };
}

async function ensureGoogleSheetsTabs(sheets, sheetId) {
  const desired = ['告發', '通檢', '案件追蹤紀錄'];
  const meta = await sheets.spreadsheets.get({ spreadsheetId: sheetId });
  const existing = new Set((meta.data.sheets || []).map((s) => s.properties.title));
  const requests = desired
    .filter((title) => !existing.has(title))
    .map((title) => ({ addSheet: { properties: { title } } }));
  if (requests.length) {
    await sheets.spreadsheets.batchUpdate({ spreadsheetId: sheetId, requestBody: { requests } });
  }
}

app.get('/health', async (req, res) => {
  res.json({ ok: true, service: 'ntpc-eems-case-review-system', status: 'running', time: nowTaipei() });
});

app.get('/api/health', async (req, res) => {
  const payload = {
    ok: true,
    service: 'EEMS聲音照相案件審核系統',
    organization: '聯韻聲學環保顧問股份有限公司',
    time: nowTaipei(),
    googleSheets: { configured: Boolean(process.env.GOOGLE_SHEET_ID), connected: false, message: '' }
  };
  try {
    const { sheets, sheetId } = await getSheetsClient();
    await sheets.spreadsheets.get({ spreadsheetId: sheetId });
    payload.googleSheets.connected = true;
    payload.googleSheets.message = 'Google Sheet 連線成功';
  } catch (err) {
    payload.googleSheets.message = err.message;
  }
  res.json(payload);
});

app.get('/api/sheet-url', (req, res) => {
  const directUrl = normalizeText(process.env.GOOGLE_SHEET_URL);
  const sheetId = normalizeText(process.env.GOOGLE_SHEET_ID);
  const url = directUrl || (sheetId ? `https://docs.google.com/spreadsheets/d/${encodeURIComponent(sheetId)}/edit` : '');
  res.json({ ok: Boolean(url), url });
});

app.get('/api/schema', (req, res) => {
  res.json(SCHEMA);
});

app.get('/api/cases', (req, res) => {
  const all = refreshRepeatFlags(readCases());
  const list = filterCases(all, req.query);
  res.json({ items: list, stats: stats(all) });
});

app.get('/api/cases/:id', (req, res) => {
  const item = refreshRepeatFlags(readCases()).find((c) => caseKey(c) === req.params.id || normalizeText(c.id) === req.params.id);
  if (!item) return res.status(404).json({ error: '找不到案件' });
  res.json(item);
});

app.post('/api/import/:type', upload.single('file'), (req, res) => {
  const type = req.params.type;
  if (!SCHEMA[type]) return res.status(400).json({ error: '案件類型僅支援告發或通檢' });
  if (!req.file) return res.status(400).json({ error: '請上傳 Excel 檔案' });

  try {
    const rows = readUploadedWorkbook(req.file.path, type);
    const incoming = rows
      .filter((row) => hasMeaningfulCaseRow(type, row))
      .map((row) => caseFromFlatRow(type, row));

    const result = upsertCases(readCases(), incoming);
    writeCases(result.cases);
    res.json({ ok: true, type, totalRows: rows.length, imported: incoming.length, inserted: result.inserted, updated: result.updated });
  } catch (err) {
    res.status(500).json({ error: err.message });
  } finally {
    try { fs.unlinkSync(req.file.path); } catch (_) {}
  }
});

app.get('/api/export/:type', (req, res) => {
  const type = req.params.type;
  if (!['告發', '通檢', '全部', 'sheet'].includes(type)) return res.status(400).json({ error: '匯出類型僅支援告發、通檢、全部或sheet' });
  const exportType = type === 'sheet' ? '全部' : type;
  const wb = makeWorkbookForCases(exportType, readCases());
  const label = type === 'sheet' ? 'GoogleSheet同格式' : exportType;
  const fileName = encodeURIComponent(`EEMS案件審核匯出_${label}_${todayTaipeiDate()}.xlsx`);
  const buffer = XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' });
  res.setHeader('Content-Disposition', `attachment; filename*=UTF-8''${fileName}`);
  res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
  res.end(buffer);
});

app.get('/api/template', (req, res) => {
  if (fs.existsSync(TEMPLATE_FILE)) return res.download(TEMPLATE_FILE);
  const wb = makeWorkbookForCases('全部', []);
  const buffer = XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' });
  res.setHeader('Content-Disposition', `attachment; filename*=UTF-8''${encodeURIComponent('EEMS案件審核匯入匯出範本.xlsx')}`);
  res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
  res.end(buffer);
});

app.get('/api/ai/dashboard', (req, res) => {
  res.json(aiDashboard(readCases()));
});

app.get('/api/ai/priority-list', (req, res) => {
  const items = refreshRepeatFlags(readCases())
    .map((item) => ({ caseId: caseKey(item), displayNo: displayCaseTitle(item), type: item.type, plate: item.source?.['車號'] || '', status: item.status, quality: aiQualityCheck(item), priority: aiPriority(item) }))
    .sort((a, b) => b.priority.score - a.priority.score);
  res.json({ ok: true, items });
});

app.get('/api/ai/admin-tasks', (req, res) => {
  res.json({ ok: true, items: aiAdminTasks(readCases()) });
});

app.get('/api/ai/cases/:id/quality', (req, res) => {
  const item = refreshRepeatFlags(readCases()).find((c) => caseKey(c) === req.params.id || normalizeText(c.id) === req.params.id);
  if (!item) return res.status(404).json({ error: '找不到案件' });
  res.json({ ok: true, caseId: caseKey(item), quality: aiQualityCheck(item), priority: aiPriority(item) });
});

app.get('/api/ai/cases/:id/summary', async (req, res) => {
  const item = refreshRepeatFlags(readCases()).find((c) => caseKey(c) === req.params.id || normalizeText(c.id) === req.params.id);
  if (!item) return res.status(404).json({ error: '找不到案件' });
  try {
    res.json({ ok: true, caseId: caseKey(item), ...(await aiSummaryEnhanced(item)) });
  } catch (err) {
    res.status(502).json({ error: err.message });
  }
});

app.get('/api/ai/cases/:id/reject-reason', async (req, res) => {
  const item = refreshRepeatFlags(readCases()).find((c) => caseKey(c) === req.params.id || normalizeText(c.id) === req.params.id);
  if (!item) return res.status(404).json({ error: '找不到案件' });
  try {
    res.json({ ok: true, caseId: caseKey(item), reason: await aiRejectReasonEnhanced(item) });
  } catch (err) {
    res.status(502).json({ error: err.message });
  }
});

app.post('/api/ai/chat', async (req, res) => {
  try {
    res.json({ ok: true, answer: await aiLineAnswerEnhanced(req.body?.query || req.body?.message || '', readCases()) });
  } catch (err) {
    res.status(502).json({ error: err.message });
  }
});


app.patch('/api/cases/:id/update', (req, res) => {
  const cases = readCases();
  const index = findCaseIndexById(cases, req.params.id);
  if (index < 0) return res.status(404).json({ error: '找不到案件' });
  const item = cases[index];
  const originalId = publicCaseNo(item);
  const newId = normalizeText(Object.prototype.hasOwnProperty.call(req.body, 'id') ? req.body.id : (req.body.newId ?? item.id));
  if (newId && newId !== originalId && cases.some((c) => publicCaseNo(c) === newId)) return res.status(409).json({ error: '案件編號已存在，無法修改' });

  const nextType = normalizeText(req.body.type || item.type);
  if (!SCHEMA[nextType]) return res.status(400).json({ error: '案件類型僅支援告發或通檢' });
  item.id = newId;
  item.type = nextType;
  if (Object.prototype.hasOwnProperty.call(req.body, 'status')) item.status = normalizeText(req.body.status) || item.status;
  item.source = item.source || {};
  const sourcePatch = req.body.source && typeof req.body.source === 'object' ? req.body.source : {};
  Object.entries(sourcePatch).forEach(([key, value]) => {
    const canonicalKey = canonicalHeader(key);
    if (SCHEMA[nextType].sourceHeaders.includes(canonicalKey)) item.source[canonicalKey] = normalizeText(value);
  });
  item.flags = item.flags || {};
  if (Object.prototype.hasOwnProperty.call(req.body, 'repeatOverLimit')) item.flags.repeatOverLimit = parseBool(req.body.repeatOverLimit);
  if (Object.prototype.hasOwnProperty.call(req.body, 'escalated')) item.flags.escalated = parseBool(req.body.escalated);
  if (Object.prototype.hasOwnProperty.call(req.body, 'repeatNote')) item.flags.repeatNote = normalizeText(req.body.repeatNote);
  if (item.flags.repeatOverLimit || item.flags.escalated) item.flags.repeatNote = item.flags.repeatNote || '車號重複超標，註明加重';
  addLog(item, '修改案件', normalizeText(req.body.operator) || '承辦人員', newId !== originalId ? `案件編號 ${originalId || '空白'} 改為 ${newId || '空白'}` : '更新案件資料');
  writeCases(cases);
  res.json({ ok: true, item });
});

app.delete('/api/cases/:id', requireDeleteAdmin, (req, res) => {
  const cases = readCases();
  const index = findCaseIndexById(cases, req.params.id);
  if (index < 0) return res.status(404).json({ error: '找不到案件' });
  const [removed] = cases.splice(index, 1);
  writeCases(cases);
  res.json({ ok: true, deleted: publicCaseNo(removed) || caseKey(removed) });
});

app.patch('/api/cases/:id/review', (req, res) => {
  const cases = readCases();
  const item = cases.find((c) => caseKey(c) === req.params.id || normalizeText(c.id) === req.params.id);
  if (!item) return res.status(404).json({ error: '找不到案件' });

  const approved = parseBool(req.body.approved);
  const reviewer = normalizeText(req.body.reviewer) || '局內長官';
  const rejectedReason = normalizeText(req.body.rejectedReason || req.body.reason);

  item.review = item.review || {};
  item.review.chiefApproved = approved;
  item.review.chiefReviewer = reviewer;
  item.review.chiefReviewedAt = todayTaipeiDate();
  item.review.rejectedReason = approved ? '' : rejectedReason;

  item.admin = item.admin || {};
  if (approved) {
    item.status = '行政處理中';
    item.admin.stage = item.admin.stage && item.admin.stage !== '尚未啟動' ? item.admin.stage : '待製作公文';
    if (item.type === '通檢' && (!item.admin.inspectionStatus || item.admin.inspectionStatus === '未啟動')) {
      item.admin.inspectionStatus = '通知待發文';
    }
    addLog(item, '長官核可', reviewer, '案件進入後續行政流程');
  } else {
    item.status = '退回修正';
    item.admin.stage = item.admin.stage || '尚未啟動';
    addLog(item, '退回修正', reviewer, rejectedReason);
  }
  writeCases(cases);
  res.json({ ok: true, item });
});

app.post('/api/cases/bulk-review', (req, res) => {
  const ids = Array.isArray(req.body.ids) ? req.body.ids : [];
  const approved = parseBool(req.body.approved);
  const reviewer = normalizeText(req.body.reviewer) || '局內長官';
  const rejectedReason = normalizeText(req.body.rejectedReason || req.body.reason);
  const cases = readCases();
  let changed = 0;

  cases.forEach((item) => {
    if (!ids.includes(caseKey(item)) && !ids.includes(normalizeText(item.id))) return;
    item.review = item.review || {};
    item.admin = item.admin || {};
    item.review.chiefApproved = approved;
    item.review.chiefReviewer = reviewer;
    item.review.chiefReviewedAt = todayTaipeiDate();
    item.review.rejectedReason = approved ? '' : rejectedReason;

    if (approved) {
      item.status = '行政處理中';
      item.admin.stage = item.admin.stage && item.admin.stage !== '尚未啟動' ? item.admin.stage : '待製作公文';
      if (item.type === '通檢' && (!item.admin.inspectionStatus || item.admin.inspectionStatus === '未啟動')) item.admin.inspectionStatus = '通知待發文';
      addLog(item, '批次長官核可', reviewer, `批次核可 ${ids.length} 件`);
    } else {
      item.status = '退回修正';
      addLog(item, '批次退回修正', reviewer, rejectedReason);
    }
    changed += 1;
  });

  writeCases(cases);
  res.json({ ok: true, changed });
});

app.patch('/api/cases/:id/admin', (req, res) => {
  const cases = readCases();
  const item = cases.find((c) => caseKey(c) === req.params.id || normalizeText(c.id) === req.params.id);
  if (!item) return res.status(404).json({ error: '找不到案件' });

  if (Object.prototype.hasOwnProperty.call(req.body, 'officialDocumentNo')) {
    const d = digitsOnly(req.body.officialDocumentNo);
    if (d && d.length !== 10) return res.status(400).json({ error: '公文文號需為10碼數字' });
    req.body.officialDocumentNo = d;
  }
  if (Object.prototype.hasOwnProperty.call(req.body, 'dispositionNo')) {
    const d = digitsOnly(req.body.dispositionNo);
    if (d && d.length !== 11) return res.status(400).json({ error: '裁處字號需為11碼數字' });
    req.body.dispositionNo = d;
  }

  const allowed = [
    'stage', 'officialDocumentNo', 'officialDocumentDate', 'dispositionNo',
    'penaltyAmount', 'deliveryDate', 'paymentStatus',
    'inspectionDueDate', 'inspectionStatus', 'closeDate', 'notes'
  ];

  item.admin = item.admin || {};
  allowed.forEach((key) => {
    if (Object.prototype.hasOwnProperty.call(req.body, key)) item.admin[key] = normalizeText(req.body[key]);
  });

  if (item.admin.closeDate || item.admin.paymentStatus === '繳款結案' || item.admin.inspectionStatus === '結案') {
    item.status = '已結案';
    item.admin.stage = item.admin.stage || '已結案';
  } else if (item.review?.chiefApproved) {
    item.status = '行政處理中';
  }

  addLog(item, '更新行政流程', '局內長官', item.admin.notes || '');
  writeCases(cases);
  res.json({ ok: true, item });
});

app.post('/api/sync/pull', async (req, res) => {
  try {
    const { sheets, sheetId } = await getSheetsClient();
    await ensureGoogleSheetsTabs(sheets, sheetId);
    const incoming = [];
    let importedWithoutCaseNo = 0;

    for (const type of ['告發', '通檢']) {
      const result = await sheets.spreadsheets.values.get({
        spreadsheetId: sheetId,
        range: `${type}!A:AZ`
      });
      const values = result.data.values || [];
      if (!values.length) continue;
      const headers = values[0];
      values.slice(1).forEach((arr) => {
        const rawRow = {};
        headers.forEach((h, idx) => { rawRow[h] = arr[idx] || ''; });
        const row = canonicalizeRow(rawRow);
        if (hasMeaningfulCaseRow(type, row)) {
          if (!normalizeText(row['案件編號'])) importedWithoutCaseNo += 1;
          incoming.push(caseFromFlatRow(type, row));
        }
      });
    }

    const result = upsertCases(readCases(), incoming);
    writeCases(result.cases);
    res.json({ ok: true, pulled: incoming.length, inserted: result.inserted, updated: result.updated, importedWithoutCaseNo });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.post('/api/sync/push', async (req, res) => {
  try {
    const { sheets, sheetId } = await getSheetsClient();
    await ensureGoogleSheetsTabs(sheets, sheetId);
    const cases = readCases();

    for (const type of ['告發', '通檢']) {
      await sheets.spreadsheets.values.clear({ spreadsheetId: sheetId, range: `${type}!A:AZ` });
      await sheets.spreadsheets.values.update({
        spreadsheetId: sheetId,
        range: `${type}!A1`,
        valueInputOption: 'RAW',
        requestBody: { values: rowsToSheetValues(type, cases) }
      });
    }

    const logRows = [['案件編號', '案件類型', '時間', '動作', '執行者', '備註']];
    cases.forEach((c) => (c.logs || []).forEach((log) => logRows.push([publicCaseNo(c), c.type, log.at, log.action, log.by, log.note])));
    await sheets.spreadsheets.values.clear({ spreadsheetId: sheetId, range: `案件追蹤紀錄!A:Z` });
    await sheets.spreadsheets.values.update({
      spreadsheetId: sheetId,
      range: `案件追蹤紀錄!A1`,
      valueInputOption: 'RAW',
      requestBody: { values: logRows }
    });

    res.json({ ok: true, pushed: cases.length });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});


app.post('/line/webhook', async (req, res) => {
  const token = process.env.LINE_WEBHOOK_SECRET;
  const provided = req.header('x-line-webhook-secret') || req.query.secret;
  if (token && provided !== token) return res.status(403).json({ error: 'LINE webhook secret 不正確' });
  const message = req.body?.message || req.body?.events?.[0]?.message?.text || req.body?.query || '';
  try {
    res.json({ ok: true, answer: await aiLineAnswerEnhanced(message, readCases()) });
  } catch (err) {
    res.status(502).json({ error: err.message });
  }
});

app.get('*', (req, res) => {
  res.sendFile(path.join(ROOT, 'public', 'index.html'));
});

app.listen(PORT, () => {
  console.log(`EEMS case review system listening on ${PORT}`);
});
